default_language_version:
  python: python3.14

repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v4.4.0
    hooks:
      - id: validate_manifest

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-ast
      - id: debug-statements
      # Conflicts with black/ruff formatting
      # - id: double-quote-string-fixer
      - id: check-docstring-first
      - id: check-illegal-windows-names
      # Git is already set up to convert to simple LF endings
      - id: mixed-line-ending
        args: [--fix=no]
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      # Linter
      - id: ruff-check
        # args: [ --fix ]
      # Formatter
      - id: ruff-format

  # Ruff already includes isort functionality
  # - repo: https://github.com/asottile/reorder-python-imports
  #   rev: v3.16.0
  #   hooks:
  #     - id: reorder-python-imports
  #       args: [--py312-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
        - polars==1.35.2

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.1
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.20.0"
    hooks:
      - id: blacken-docs
        additional_dependencies:
        - black==25.11.0

  - repo: https://github.com/crate-ci/typos
    rev: v1.39.0
    hooks:
      - id: typos

  # zizmor detects security vulnerabilities in GitHub Actions workflows.
  # Additional configuration for the tool is found in `.github/zizmor.yml`
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.16.3
    hooks:
      - id: zizmor

  # Disabled for now, as it cannot work with YAML anchors and shellcheck had errors.
  # `actionlint` hook, for verifying correct syntax in GitHub Actions workflows.
  # Some additional configuration for `actionlint` can be found in `.github/actionlint.yaml`.
  # - repo: https://github.com/rhysd/actionlint
  #   rev: v1.7.7
  #   hooks:
  #     - id: actionlint
  #       # stages:
  #         # This hook is disabled by default, since it's quite slow.
  #         # To run all hooks *including* this hook, use `uvx pre-commit run -a --hook-stage=manual`.
  #         # To run *just* this hook, use `uvx pre-commit run -a actionlint --hook-stage=manual`.
  #       #   - manual
  #       # args:
  #       #   - "-ignore=SC2129" # ignorable stylistic lint from shellcheck
  #       #   - "-ignore=SC2016" # another shellcheck lint: seems to have false positives?
  #       additional_dependencies:
  #         # actionlint has a shellcheck integration which extracts shell scripts in `run:` steps from GitHub Actions
  #         # and checks these with shellcheck. This is arguably its most useful feature,
  #         # but the integration only works if shellcheck is installed
  #         - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.10.0"

  - repo: local
    hooks:
    - id: nox-tests
      name: Run tests with nox
      entry: nox
      args: ["-t", "pre-commit"]
      language: system
      pass_filenames: false
      types: [python]
      verbose: true
