---
name: build documentation

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: build documentation, coverage and badge
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.14"]
        os: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3  # v7.1.3
        with:
          enable-cache: true

      - name: run tests & coverage report
        run: uvx nox -s tests_with_coverage --force-python ${{ matrix.python-version }}

      - name: extract coverage badge data
        run: python ${{ github.workspace }}/.github/scripts/extract_coverage.py

      - name: upload coverage badge
        uses: actions/upload-artifact@v5
        with:
          name: coverage-badge
          path: badges/coverage.json
          if-no-files-found: error

      - name: upload coverage HTML report
        uses: actions/upload-artifact@v5
        with:
          name: coverage-html
          path: htmlcov/
          if-no-files-found: error

      - name: build documentation
        run: uvx nox -s docs --force-python ${{ matrix.python-version }}

      - name: upload documnentation HTML
        uses: actions/upload-artifact@v5
        with:
          name: documentation-html
          path: ./docs/_build/html
          if-no-files-found: error

  docs:
    name: deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: download documentation HTML artifact
        uses: actions/download-artifact@v6
        with:
          name: documentation-html
          path: ./html

      - name: download coverage badge artifact
        uses: actions/download-artifact@v6
        with:
          name: coverage-badge
          path: ./html/badges

      - name: download coverage HTML report artifact
        uses: actions/download-artifact@v6
        with:
          name: coverage-html
          path: ./html/htmlcov

      - name: make combined artifact available to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./html

      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
